# Generated by Django 5.2.1 on 2025-05-27 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('rxn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_presentacion_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificacion', models.TextField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KitReactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_presentacion_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads', models.IntegerField()),
                ('reads_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bibliotecas_pflowcel', models.IntegerField()),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.kitreactivo')),
            ],
        ),
        migrations.CreateModel(
            name='CostoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_flowcell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_ibt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_secuenciacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.consumible')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.kitreactivo')),
            ],
        ),
        migrations.AddField(
            model_name='kitreactivo',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma'),
        ),
        migrations.CreateModel(
            name='Cuantificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='consumible',
            name='plataforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma'),
        ),
        migrations.CreateModel(
            name='BufferGelOligo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('buffer_gel_oligo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.buffergeloligo')),
                ('consumible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.consumible')),
                ('cuantificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.cuantificacion')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.proceso')),
                ('reactivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.reactivo')),
            ],
        ),
        migrations.CreateModel(
            name='CuantificacionConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('buffer_gel_oligo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.buffergeloligo')),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.consumible')),
                ('cuantificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.cuantificacion')),
                ('reactivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.reactivo')),
            ],
        ),
        migrations.CreateModel(
            name='BGOConsumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('bgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.buffergeloligo')),
                ('consumible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.consumible')),
                ('cuantificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.cuantificacion')),
                ('reactivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.reactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.proceso')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.servicio')),
            ],
        ),
    ]
