# Generated by Django 5.2.1 on 2025-06-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_costos', '0002_alter_consumible_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reactivo',
            name='plataforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_costos.plataforma'),
        ),
    ]
