# Generated by Django 5.2.1 on 2025-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_costos', '0003_reactivo_fecha_actualizacion_reactivo_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('respuestas', models.JSONField()),
                ('costo_total', models.FloatField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
